<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LibObjectFile\.dockerignore" />
    <None Remove="LibObjectFile\LibObjectFile.sln.DotSettings" />
    <None Remove="LibObjectFile\LibObjectFile\LibObjectFile.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
  </ItemGroup>

</Project>
