<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LibObjectFile\.dockerignore" />
    <None Remove="LibObjectFile\LibObjectFile.sln.DotSettings" />
    <None Remove="LibObjectFile\LibObjectFile\LibObjectFile.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibObjectFile" Version="2.1.1" />
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GitHub\FluentArgs\source\FluentArgs\FluentArgs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FluentArgs">
      <HintPath>..\..\..\GitHub\FluentArgs\source\FluentArgs\bin\Debug\netstandard2.0\FluentArgs.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
