<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LibObjectFile\.dockerignore" />
    <None Remove="LibObjectFile\LibObjectFile.sln.DotSettings" />
    <None Remove="LibObjectFile\LibObjectFile\LibObjectFile.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibObjectFile" Version="2.1.1" />
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\GitHub\FluentArgs\source\FluentArgs\FluentArgs.csproj" />
  </ItemGroup>

</Project>
