#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981,SYSLIB1092
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using Devices.DeviceAndDriverInstallation;
using Microsoft.Win32;
using Windows.Win32.Devices.DeviceAndDriverInstallation;
using Windows.Win32.Devices.Usb;
using Windows.Win32.Foundation;
using winmdroot = global::Windows.Win32;

namespace CsWin32Api
{
    public class SetupDeviceInterfaceDataDetail
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="SetupDeviceInterfaceDataDetail"/> class.
        /// </summary>
        /// <param name="src">The source.</param>
        internal SetupDeviceInterfaceDataDetail(SP_DEVICE_INTERFACE_DETAIL_DATA_W src) : this(new SP_DEVICE_INTERFACE_DETAIL_DATA_W2())
        {
            // TODO: Revice!
        }

        internal SetupDeviceInterfaceDataDetail(SP_DEVICE_INTERFACE_DETAIL_DATA_W2 src)
        {
            this._src = src;
            this._src.cbSize = (uint)Marshal.SizeOf<SP_DEVICE_INTERFACE_DETAIL_DATA_W2>();
            this._src.DevicePathStr = string.Empty;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SetupDeviceInterfaceDataDetail"/> class.
        /// </summary>
        public SetupDeviceInterfaceDataDetail() : this(new SP_DEVICE_INTERFACE_DETAIL_DATA_W2())
        {
        }

        // Member variables
        internal SP_DEVICE_INTERFACE_DETAIL_DATA_W2 _src;


        // properties
        /// <summary>
        /// Gets the size of the class structure.
        /// </summary>
        /// <value>
        /// The size of the cb.
        /// </value>
        public uint CbSize { get => this._src.cbSize; set => this._src.cbSize = value; }

        /// <summary>
        /// Gets the device path2.
        /// </summary>
        /// <value>
        /// The device path2.
        /// </value>
        public string DevicePathStr
        {
            get
            {
                return this._src.DevicePathStr;
            }
            set
            {
                this._src.DevicePathStr = value;
            }
        }

        /// <summary>Computes the amount of memory that must be allocated to store this struct, including the specified number of elements in the variable length inline array at the end.</summary>
        public static unsafe int SizeOf(int count)
        {
            return SP_DEVICE_INTERFACE_DETAIL_DATA_W.SizeOf(count);
        }

        public override string ToString()
        {
            return $"CbSize {CbSize}, DevicePath: {DevicePathStr}";
        }
    }

}

namespace Devices.DeviceAndDriverInstallation
{
    /// <summary>An SP_DEVICE_INTERFACE_DETAIL_DATA_W2 structure contains the path for a device interface. (Unicode)</summary>
    /// <remarks>
    /// <para>
    /// Used SP_DEVICE_INTERFACE_DETAIL_DATA_W2 instead of SP_DEVICE_INTERFACE_DETAIL_DATA_W with Windows.Win32.PInvoke.SetupDiGetDeviceInterfaceDetail2.
    /// Dont use Windows.Win32.PInvoke.SetupDiGetDeviceInterfaceDetail autogenerated not working.
    /// </para>
    /// <para>An SP_DEVICE_INTERFACE_DETAIL_DATAW2 structure identifies the path for a device interface in a device information set. <b>SetupDi</b><i>Xxx</i> functions that take an SP_DEVICE_INTERFACE_DETAIL_DATA structure as a parameter verify that the <b>cbSize</b> member of the supplied structure is equal to the size, in bytes, of the structure. If the <b>cbSize</b> member is not set correctly for an input parameter, the function will fail and set an error code of ERROR_INVALID_PARAMETER. If the <b>cbSize</b> member is not set correctly for an output parameter, the function will fail and set an error code of ERROR_INVALID_USER_BUFFER.</para>
    /// </remarks>
    internal struct SP_DEVICE_INTERFACE_DETAIL_DATA_W2
    {
        /// <summary>A NULL-terminated string that contains the device interface path. This path can be passed to Win32 functions such as <a href="https://docs.microsoft.com/windows/desktop/api/fileapi/nf-fileapi-createfilea">CreateFile</a>.</summary>
        //internal char[] DevicePath = new char[ANYSIZE_ARRAY];

        internal uint cbSize;
        internal string DevicePathStr;

        /// <summary>Computes the amount of memory that must be allocated to store this struct, including the specified number of elements in the variable length inline array at the end.</summary>
        internal static unsafe int SizeOf(int count)
        {
            int v = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA_W);
            if (count > 1)
                v += checked((count - 1) * sizeof(char));
            else
                    if (count < 0)
                throw new ArgumentOutOfRangeException();
            return v;
        }
    }
}
