using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.Win32.Devices.DeviceAndDriverInstallation;
namespace CsWin32Api
{
    public static class UsbConstants
    {
        public static Guid GUID_DEVINTERFACE_USB_HUB = Guid.Parse("{f18a0e88-c30c-11d0-8815-00a0c906bed8}");
        public static Guid GUID_DEVINTERFACE_USB_BILLBOARD = Guid.Parse("{5e9adaef-f879-473f-b807-4e5ea77d1b1c}");
        public static Guid GUID_DEVINTERFACE_USB_DEVICE = Guid.Parse("{A5DCBF10-6530-11D2-901F-00C04FB951ED}");
        public static Guid GUID_DEVINTERFACE_USB_HOST_CONTROLLER = Guid.Parse("{3ABF6F2D-71C4-462a-8A92-1E6861E6AF27}");
        public static Guid GUID_USB_WMI_STD_DATA = Guid.Parse("{4E623B20-CB14-11D1-B331-00A0C959BBD2}");
        public static Guid GUID_USB_WMI_STD_NOTIFICATION = Guid.Parse("{4E623B20-CB14-11D1-B331-00A0C959BBD2}");
        public static Guid GUID_USB_WMI_DEVICE_PERF_INFO = Guid.Parse("{66C1AA3C-499F-49a0-A9A5-61E2359F6407}");
        public static Guid GUID_USB_WMI_NODE_INFO = Guid.Parse("{9C179357-DC7A-4f41-B66B-323B9DDCB5B1}");
        public static Guid GUID_USB_WMI_TRACING = Guid.Parse("{3a61881b-b4e6-4bf9-ae0f-3cd8f394e52f}");
        public static Guid GUID_USB_TRANSFER_TRACING = Guid.Parse("{681EB8AA-403D-452c-9F8A-F0616FAC9540}");
        public static Guid GUID_USB_PERFORMANCE_TRACING = Guid.Parse("{D5DE77A6-6AE9-425c-B1E2-F5615FD348A9}");
        public static Guid GUID_USB_WMI_SURPRISE_REMOVAL_NOTIFICATION = Guid.Parse("{9BBBF831-A2F2-43B4-96D1-86944B5914B3}");

    }

    // Function codes for kernel mode IOCTLs with DeviceType : DEVICE_TYPE_USB (a.k.a DEVICE_TYPE_UNKNOWN)

    // The following codes are valid only if passed as in
    // the icControlCode parameter for IRP_MJ_INTERNAL_DEVICE_CONTROL

    public enum DEVICE_TYPE_USB : uint
    {
        USB_SUBMIT_URB = 0,
        USB_RESET_PORT = 1,
        USB_GET_ROOTHUB_PDO = 3,
        USB_GET_PORT_STATUS = 4,
        USB_ENABLE_PORT = 5,
        USB_GET_HUB_COUNT = 6,
        USB_CYCLE_PORT = 7,
        USB_GET_HUB_NAME = 8,
        USB_IDLE_NOTIFICATION = 9,
        USB_RECORD_FAILURE = 10,
        USB_GET_BUS_INFO = 264,
        USB_GET_CONTROLLER_NAME = 265,
        USB_GET_BUSGUID_INFO = 266,
        USB_GET_PARENT_HUB_INFO = 267,
        USB_GET_DEVICE_HANDLE = 268,
        USB_GET_DEVICE_HANDLE_EX = 269,
        USB_GET_TT_DEVICE_HANDLE = 270,
        USB_GET_TOPOLOGY_ADDRESS = 271,
        USB_IDLE_NOTIFICATION_EX = 272,
        USB_REQ_GLOBAL_SUSPEND = 273,
        USB_REQ_GLOBAL_RESUME = 274,
        USB_GET_HUB_CONFIG_INFO = 275,
        USB_FAIL_GET_STATUS = 280
    }

    //
    // Function codes for kernel mode IOCTLs with DeviceType : DEVICE_TYPE_USBEX
    //
    // The following codes are valid only if passed as in
    // the icControlCode parameter for
    // IRP_MJ_INTERNAL_DEVICE_CONTROL

    // The range 0 - 2047 is reserved for use by Microsoft.
    // The range 0 - 1023 is used for Public Ioctls defined by Microsoft.

    //
    public enum DEVICE_TYPE_USBEX
    {
        USB_REGISTER_COMPOSITE_DEVICE = 0,
        USB_UNREGISTER_COMPOSITE_DEVICE = 1,
        USB_REQUEST_REMOTE_WAKE_NOTIFICATION = 2
    }

    public enum SpDiRegisteryProperty : uint
    {
        //
        // Device registry property codes
        // (Codes marked as read-only (R) may only be used for
        // SetupDiGetDeviceRegistryProperty)
        //
        // These values should cover the same set of registry properties
        // as defined by the CM_DRP codes in cfgmgr32.h.
        //
        // Note that SPDRP codes are zero based while CM_DRP codes are one based!
        //
        SPDRP_DEVICEDESC = SETUP_DI_REGISTRY_PROPERTY.SPDRP_DEVICEDESC,
        SPDRP_HARDWAREID = SETUP_DI_REGISTRY_PROPERTY.SPDRP_HARDWAREID,
        SPDRP_COMPATIBLEIDS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_COMPATIBLEIDS,
        SPDRP_UNUSED0 = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UNUSED0,
        SPDRP_SERVICE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_SERVICE,
        SPDRP_UNUSED1 = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UNUSED1,
        SPDRP_UNUSED2 = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UNUSED2,
        SPDRP_CLASS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_CLASS,
        SPDRP_CLASSGUID = SETUP_DI_REGISTRY_PROPERTY.SPDRP_CLASSGUID,
        SPDRP_DRIVER = SETUP_DI_REGISTRY_PROPERTY.SPDRP_DRIVER,
        SPDRP_CONFIGFLAGS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_CONFIGFLAGS,
        SPDRP_MFG = SETUP_DI_REGISTRY_PROPERTY.SPDRP_MFG,
        SPDRP_FRIENDLYNAME = SETUP_DI_REGISTRY_PROPERTY.SPDRP_FRIENDLYNAME,
        SPDRP_LOCATION_INFORMATION = SETUP_DI_REGISTRY_PROPERTY.SPDRP_LOCATION_INFORMATION,
        SPDRP_PHYSICAL_DEVICE_OBJECT_NAME = SETUP_DI_REGISTRY_PROPERTY.SPDRP_PHYSICAL_DEVICE_OBJECT_NAME,
        SPDRP_CAPABILITIES = SETUP_DI_REGISTRY_PROPERTY.SPDRP_CAPABILITIES,
        SPDRP_UI_NUMBER = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UI_NUMBER,
        SPDRP_UPPERFILTERS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UPPERFILTERS,
        SPDRP_LOWERFILTERS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_LOWERFILTERS,
        SPDRP_BUSTYPEGUID = SETUP_DI_REGISTRY_PROPERTY.SPDRP_BUSTYPEGUID,
        SPDRP_LEGACYBUSTYPE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_LEGACYBUSTYPE,
        SPDRP_BUSNUMBER = SETUP_DI_REGISTRY_PROPERTY.SPDRP_LEGACYBUSTYPE,
        SPDRP_ENUMERATOR_NAME = SETUP_DI_REGISTRY_PROPERTY.SPDRP_ENUMERATOR_NAME,
        SPDRP_SECURITY = SETUP_DI_REGISTRY_PROPERTY.SPDRP_SECURITY,
        SPDRP_SECURITY_SDS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_SECURITY_SDS,
        SPDRP_DEVTYPE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_DEVTYPE,
        SPDRP_EXCLUSIVE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_EXCLUSIVE,
        SPDRP_CHARACTERISTICS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_CHARACTERISTICS,
        SPDRP_ADDRESS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_ADDRESS,
        SPDRP_UI_NUMBER_DESC_FORMAT = SETUP_DI_REGISTRY_PROPERTY.SPDRP_UI_NUMBER_DESC_FORMAT,
        SPDRP_DEVICE_POWER_DATA = SETUP_DI_REGISTRY_PROPERTY.SPDRP_DEVICE_POWER_DATA,
        SPDRP_REMOVAL_POLICY = SETUP_DI_REGISTRY_PROPERTY.SPDRP_REMOVAL_POLICY,
        SPDRP_REMOVAL_POLICY_HW_DEFAULT = SETUP_DI_REGISTRY_PROPERTY.SPDRP_REMOVAL_POLICY_HW_DEFAULT,
        SPDRP_REMOVAL_POLICY_OVERRIDE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_REMOVAL_POLICY_OVERRIDE,
        SPDRP_INSTALL_STATE = SETUP_DI_REGISTRY_PROPERTY.SPDRP_INSTALL_STATE,
        SPDRP_LOCATION_PATHS = SETUP_DI_REGISTRY_PROPERTY.SPDRP_LOCATION_PATHS,
        SPDRP_BASE_CONTAINERID = SETUP_DI_REGISTRY_PROPERTY.SPDRP_BASE_CONTAINERID,
        SPDRP_MAXIMUM_PROPERTY = SETUP_DI_REGISTRY_PROPERTY.SPDRP_MAXIMUM_PROPERTY
    }

}