using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.Win32.Devices.Properties;

namespace CsWin32Api
{

    public enum DevPropType : uint
    {
        DEVPROP_TYPEMOD_ARRAY = DEVPROPTYPE.DEVPROP_TYPEMOD_ARRAY,
        DEVPROP_TYPEMOD_LIST = DEVPROPTYPE.DEVPROP_TYPEMOD_LIST,
        DEVPROP_TYPE_EMPTY = DEVPROPTYPE.DEVPROP_TYPE_EMPTY,
        DEVPROP_TYPE_NULL = DEVPROPTYPE.DEVPROP_TYPE_NULL,
        DEVPROP_TYPE_SBYTE = DEVPROPTYPE.DEVPROP_TYPE_SBYTE,
        DEVPROP_TYPE_BYTE = DEVPROPTYPE.DEVPROP_TYPE_BYTE,
        DEVPROP_TYPE_INT16 = DEVPROPTYPE.DEVPROP_TYPE_INT16,
        DEVPROP_TYPE_UINT16 = DEVPROPTYPE.DEVPROP_TYPE_UINT16,
        DEVPROP_TYPE_INT32 = DEVPROPTYPE.DEVPROP_TYPE_UINT32,
        DEVPROP_TYPE_UINT32 = DEVPROPTYPE.DEVPROP_TYPE_UINT32,
        DEVPROP_TYPE_INT64 = DEVPROPTYPE.DEVPROP_TYPE_INT64,
        DEVPROP_TYPE_UINT64 = DEVPROPTYPE.DEVPROP_TYPE_INT64,
        DEVPROP_TYPE_FLOAT = DEVPROPTYPE.DEVPROP_TYPE_FLOAT,
        DEVPROP_TYPE_DOUBLE = DEVPROPTYPE.DEVPROP_TYPE_DOUBLE,
        DEVPROP_TYPE_DECIMAL = DEVPROPTYPE.DEVPROP_TYPE_DECIMAL,
        DEVPROP_TYPE_GUID = DEVPROPTYPE.DEVPROP_TYPE_GUID,
        DEVPROP_TYPE_CURRENCY = DEVPROPTYPE.DEVPROP_TYPE_CURRENCY,
        DEVPROP_TYPE_DATE = DEVPROPTYPE.DEVPROP_TYPE_DATE,
        DEVPROP_TYPE_FILETIME = DEVPROPTYPE.DEVPROP_TYPE_FILETIME,
        DEVPROP_TYPE_BOOLEAN = DEVPROPTYPE.DEVPROP_TYPE_BOOLEAN,
        DEVPROP_TYPE_STRING = DEVPROPTYPE.DEVPROP_TYPE_STRING,
        DEVPROP_TYPE_STRING_LIST = DEVPROPTYPE.DEVPROP_TYPE_STRING_LIST,
        DEVPROP_TYPE_SECURITY_DESCRIPTOR = DEVPROPTYPE.DEVPROP_TYPE_SECURITY_DESCRIPTOR,
        DEVPROP_TYPE_SECURITY_DESCRIPTOR_STRING = DEVPROPTYPE.DEVPROP_TYPE_SECURITY_DESCRIPTOR_STRING,
        DEVPROP_TYPE_DEVPROPKEY = DEVPROPTYPE.DEVPROP_TYPE_DEVPROPKEY,
        DEVPROP_TYPE_DEVPROPTYPE = DEVPROPTYPE.DEVPROP_TYPE_DEVPROPTYPE,
        DEVPROP_TYPE_BINARY = DEVPROPTYPE.DEVPROP_TYPE_BINARY,
        DEVPROP_TYPE_ERROR = DEVPROPTYPE.DEVPROP_TYPE_ERROR,
        DEVPROP_TYPE_NTSTATUS = DEVPROPTYPE.DEVPROP_TYPE_NTSTATUS,
        DEVPROP_TYPE_STRING_INDIRECT = DEVPROPTYPE.DEVPROP_TYPE_STRING_INDIRECT,
    }
}
