///////////////////////////////////////////////////////////
//  IHostDeviceService.cs
//  Implementation of the Interface IHostDeviceService
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2026 19:05:15
//  Original author: Alain Dupont
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using JTAGICEmkII.HostService;
using JTAGICEmkII.Slave;

namespace JTAGICEmkII
{
	public interface IHostDeviceService  
    {
        ResponseSignOn SignOnResponse { get; set; }

        TargetState TargetMcuState { get; set; }

        ICommandResult SignOff();

		ICommandResult SignOn(out ResponseSignOn? response);

        ICommandResult GetSync();

        /// 
        /// <param name="MemType"></param>
        /// <param name="Address"></param>
        /// <param name="Values"></param>
        ICommandResult WriteMemory(int MemType, ulong Address, byte[] Values);

		/// 
		/// <param name="memType"></param>
		/// <param name="Address"></param>
		/// <param name="Length"></param>
		/// <param name="Values"></param>
		ICommandResult ReadMemory(int memType, ulong Address, ulong Length, out byte[] Values);

        /// 
        /// <param name="Info"></param>
        //ICommandResult GetTargetInfo(out DeviceInfo Info);

        /// 
        /// <param name="param"></param>
        ICommandResult GetParameter(int paramId, out uint value);

        ICommandResult SetParameter(int paramId, uint value);

		/// 
		/// <param name="ProgramCounter"></param>
		ICommandResult WriteProgramCount(ulong ProgramCounter);

		/// 
		/// <param name="ProgramCounter"></param>
		ICommandResult ReadProgramCount(out ulong ProgramCounter);

		ICommandResult StartRunning();

		ICommandResult StopRunning();

		/// 
		/// <param name="Breakpoint"></param>
		ICommandResult StartRunningUntil(ulong Breakpoint);

		/// 
		/// <param name="ProgramCounter"></param>
		ICommandResult StepIn(ulong ProgramCounter);

		ICommandResult Reset();

		/// 
		/// <param name="MemType"></param>
		/// <param name="Address"></param>
		/// <param name="Length"></param>
		ICommandResult EraseMemory(int MemType, ulong Address, ulong Length);

		ICommandResult Reconnect();

		/// 
		/// <param name="index"></param>
		/// <param name="Breakpoint"></param>
		/// <param name="BreakpointType"></param>
		/// <param name="BrakpointMode"></param>
		ICommandResult SetBreakpoint(int index, ulong Breakpoint, int BreakpointType, int BrakpointMode);

		/// 
		/// <param name="Index"></param>
		/// <param name="Breakpoint"></param>
		/// <param name="BreakpointType"></param>
		/// <param name="BrakpointMode"></param>
		ICommandResult GetBreakpoint(int Index, ulong Breakpoint, int BreakpointType, int BrakpointMode);

		ICommandResult EraseDevice();

		ICommandResult EnterPrograming();

		ICommandResult LeavePrograming();

		ICommandResult VerifiyPrograming();

		/// 
		/// <param name="Address"></param>
		/// <param name="Values"></param>
		ICommandResult WritePrograming(ulong Address, byte Values);

		/// 
		/// <param name="Index"></param>
		/// <param name="Breakpoint"></param>
		ICommandResult ClearBreakpoint(int Index, ulong Breakpoint);

        ICommandResult SetDeviceDescriptor();

        ICommandResult ClearEvents();

        ICommandResult SetAllParameter();

        ICommandResult GetAllParameter();

        bool ModifyAllParameter();

        // for host caller if needed
        event EventHandler<RequestEventArgs>? RequestCompleted;
        event EventHandler<EventReceivedEventArgs>? EventReceived;
        event EventHandler<RequestEventArgs>? RequestTimeout;
        event EventHandler<ResponseReceivedEventArgs>? ResponseReceived;
        event EventHandler<CommandReceivedEventArgs>? CommandReceived;

    }
}