///////////////////////////////////////////////////////////
//  IHostDeviceService.cs
//  Implementation of the Interface IHostDeviceService
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2026 19:05:15
//  Original author: Alain Dupont
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using JTAGICEmkII.HostService;
using JTAGICEmkII.Slave;

namespace JTAGICEmkII
{
	public interface IHostDeviceService  
    {
        ResponseSignOn SignOnResponse { get; set; }

        TargetState TargetMcuState { get; set; }

        bool SignOff();

		bool SignOn(out ResponseSignOn? response);

        bool GetSync();

        /// 
        /// <param name="MemType"></param>
        /// <param name="Address"></param>
        /// <param name="Values"></param>
        bool WriteMemory(int MemType, ulong Address, byte[] Values);

		/// 
		/// <param name="memType"></param>
		/// <param name="Address"></param>
		/// <param name="Length"></param>
		/// <param name="Values"></param>
		bool ReadMemory(int memType, ulong Address, ulong Length, out byte[] Values);

        /// 
        /// <param name="Info"></param>
        //bool GetTargetInfo(out DeviceInfo Info);

        /// 
        /// <param name="param"></param>
        bool GetParameter(int paramId, out uint value);

        bool SetParameter(int paramId, uint value);

		/// 
		/// <param name="ProgramCounter"></param>
		bool WriteProgramCount(ulong ProgramCounter);

		/// 
		/// <param name="ProgramCounter"></param>
		bool ReadProgramCount(out ulong ProgramCounter);

		bool StartRunning();

		bool StopRunning();

		/// 
		/// <param name="Breakpoint"></param>
		bool StartRunningUntil(ulong Breakpoint);

		/// 
		/// <param name="ProgramCounter"></param>
		bool StepIn(ulong ProgramCounter);

		bool Reset();

		/// 
		/// <param name="MemType"></param>
		/// <param name="Address"></param>
		/// <param name="Length"></param>
		bool EraseMemory(int MemType, ulong Address, ulong Length);

		bool Reconnect();

		/// 
		/// <param name="index"></param>
		/// <param name="Breakpoint"></param>
		/// <param name="BreakpointType"></param>
		/// <param name="BrakpointMode"></param>
		bool SetBreakpoint(int index, ulong Breakpoint, int BreakpointType, int BrakpointMode);

		/// 
		/// <param name="Index"></param>
		/// <param name="Breakpoint"></param>
		/// <param name="BreakpointType"></param>
		/// <param name="BrakpointMode"></param>
		bool GetBreakpoint(int Index, ulong Breakpoint, int BreakpointType, int BrakpointMode);

		bool EraseDevice();

		bool EnterPrograming();

		bool LeavePrograming();

		bool VerifiyPrograming();

		/// 
		/// <param name="Address"></param>
		/// <param name="Values"></param>
		bool WritePrograming(ulong Address, byte Values);

		/// 
		/// <param name="Index"></param>
		/// <param name="Breakpoint"></param>
		bool ClearBreakpoint(int Index, ulong Breakpoint);

        bool SetDeviceDescriptor();

        bool ClearEvents();

        bool SetAllParameter();

        bool GetAllParameter();

        bool ModifyAllParameter();

        // for host caller if needed
        event EventHandler<RequestEventArgs>? RequestCompleted;
        event EventHandler<EventReceivedEventArgs>? EventReceived;
        event EventHandler<RequestEventArgs>? RequestTimeout;
        event EventHandler<ResponseReceivedEventArgs>? ResponseReceived;
        event EventHandler<CommandReceivedEventArgs>? CommandReceived;

    }
}