///////////////////////////////////////////////////////////
//  IHostDeviceService.cs
//  Implementation of the Interface IHostDeviceService
//  Generated by Enterprise Architect
//  Created on:      04-Apr-2026 19:05:15
//  Original author: Alain Dupont
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using JTAGICEmkII.HostService;
using JTAGICEmkII.Slave;

namespace JTAGICEmkII
{
	public interface IHostDeviceService  
    {
        ResponseSignOn SignOnResponse { get; }

        TargetState TargetMcuState { get; }

        ICommandResult SignOff();

		ICommandResult SignOn(out ResponseSignOn? response);

        ICommandResult GetSync();

        /// 
        /// <param name="memType"></param>
        /// <param name="address"></param>
        /// <param name="values"></param>
        ICommandResult WriteMemory(int memType, ulong address, byte[] values);

		/// 
		/// <param name="memType"></param>
		/// <param name="address"></param>
		/// <param name="length"></param>
		/// <param name="values"></param>
		ICommandResult ReadMemory(int memType, ulong address, ulong length, out byte[] values);

        /// 
        /// <param name="Info"></param>
        //ICommandResult GetTargetInfo(out DeviceInfo Info);

        /// 
        /// <param name="param"></param>
        ICommandResult GetParameter(int paramId, out uint value);

        ICommandResult SetParameter(int paramId, uint value);

		/// 
		/// <param name="programCounter"></param>
		ICommandResult WriteProgramCounter(ulong programCounter);

		/// 
		/// <param name="programCounter"></param>
		ICommandResult ReadProgramCounter(out ulong programCounter);

		ICommandResult StartRunning();

		ICommandResult StopRunning();

		/// 
		/// <param name="breakpoint"></param>
		ICommandResult StartRunningUntil(ulong breakpoint);

		/// 
		/// <param name="programCounter"></param>
		ICommandResult StepIn(ulong programCounter);

		ICommandResult Reset();

		/// 
		/// <param name="memType"></param>
		/// <param name="address"></param>
		/// <param name="length"></param>
		ICommandResult EraseMemory(int memType, ulong address, ulong length);

		ICommandResult Reconnect();

		/// 
		/// <param name="index"></param>
		/// <param name="breakpoint"></param>
		/// <param name="breakpointType"></param>
		/// <param name="brakpointMode"></param>
		ICommandResult SetBreakpoint(int index, ulong breakpoint, int breakpointType, int brakpointMode);

		/// 
		/// <param name="index"></param>
		/// <param name="breakpointType"></param>
		/// <param name="brakpointMode"></param>
		ICommandResult GetBreakpoint(int index, int breakpointType, int brakpointMode, out ulong breakpoint);

		ICommandResult EraseDevice();

		ICommandResult EnterPrograming();

		ICommandResult LeavePrograming();

		ICommandResult VerifiyPrograming();

		/// 
		/// <param name="address"></param>
		/// <param name="values"></param>
		ICommandResult WritePrograming(ulong address, byte values);

		/// 
		/// <param name="index"></param>
		/// <param name="breakpoint"></param>
		ICommandResult ClearBreakpoint(int index, ulong breakpoint);

        ICommandResult SetDeviceDescriptor();

        ICommandResult ClearEvents();

        ICommandResult SetAllParameter();

        ICommandResult SelfTest();

        ICommandResult GetAllParameter();

        ICommandResult SpiCommand(byte[] send, out byte read);

        bool ModifyAllParameter();

        // for host caller if needed
        event EventHandler<RequestEventArgs>? RequestCompleted;
        event EventHandler<EventReceivedEventArgs>? EventReceived;
        event EventHandler<RequestEventArgs>? RequestTimeout;
        event EventHandler<ResponseReceivedEventArgs>? ResponseReceived;
        event EventHandler<CommandReceivedEventArgs>? CommandReceived;

    }
}