<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>

</Project>
